version: '3.7'
services:
  metabase:
    image: metabase
    build: ./metabase
    container_name: metabase
    ports:
      - 3000:3000
    volumes:
      - ./datagen/yfinance.duckdb:/usr/app/data/yfinance.duckdb